# Generated by Django 4.2.16 on 2024-09-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_rename_name_education_personal_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(default='', max_length=100),
        ),
    ]
